### ISSUE TITLE
Enlaces erróneos en la URL https://jaime.gomezobregon.com/yo

### ISSUE THREAD

**Issue by oscaretu** [JaimeObregon/jaime.gomezobregon.com#11]
Hola, Jaime.

Los enlaces de tu página [https://jaime.gomezobregon.com/yo](https://jaime.gomezobregon.com/yo) no están funcionando correctamente. No fallan, pero no llevan al sitio esperado, porque faltan los ":" detrás del https. Esto es, las URL tienen `https//` en vez de `https://`, con lo que el navegador las considera URLs relativas a la página actual, y si haces clic en los enlaces, acabas volviendo a la página actual.

**Comment by JaimeObregon** [comment]
¡Gracias, @oscaretu! Acabo de resolverlo.
