### ISSUE TITLE
No back

### ISSUE THREAD

**Issue by fmrtn** [JaimeObregon/jaime.gomezobregon.com#16]
Hay un bug que no te permite retroceder a la página anterior.

Para reproducirlo:

1. Acceder a https://jaime.gomezobregon.com/
2. Pulsar en el enlace que lleva a https://jaime.gomezobregon.com/yo
3. Pulsa el botón de retroceso en el navegador (Alt + ←)

Al producirse le fallo también deja de funcionar el botón de retroceso que hay en la propia web.

Probado con: Brave y Firefox.

**Comment by JaimeObregon** [comment]
Resuelto. Gracias, @fmrtn.
